name: Simple Node Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup Node version
        uses: actions/setup-node@v4
        with:
          node-version: lts/Hydrogen

      - run: node helloworld.js
